# A Fresh Start

#### LCO - Mastering numpy

In [1]:
myList = [1,23,4,5,6]

In [2]:
import numpy as np

In [3]:
myOneDArray = np.array(myList)

In [4]:
myOneDArray

array([ 1, 23,  4,  5,  6])

In [5]:
myTwoList = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [6]:
myTwoDarray = np.array(myTwoList)

In [7]:
myTwoDarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [9]:
np.zeros(1)
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# Second Chapter

In [10]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [11]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(5,5)

array([[0.20233333, 0.95040592, 0.95088486, 0.79974569, 0.20059053],
       [0.5870002 , 0.03974562, 0.04909455, 0.73374416, 0.72906986],
       [0.68492431, 0.05023377, 0.16444752, 0.06292673, 0.66096796],
       [0.11332407, 0.51613197, 0.19671405, 0.38537665, 0.20099574],
       [0.59638141, 0.12719806, 0.52020206, 0.70126722, 0.06773466]])

In [13]:
np.random.randn(5,5)

array([[-1.18768838, -0.66780529, -2.04722573,  0.7599397 , -1.65777376],
       [-0.10364565, -0.26091806, -0.49028354, -1.52852135, -0.07196059],
       [ 0.08497143, -0.29065349,  0.67472352,  0.63427531,  0.54253857],
       [ 1.69644624, -1.08053845,  1.37760891, -0.55279418,  1.00546968],
       [ 0.1229895 , -1.03225651,  0.73069897, -1.2320818 , -0.79891908]])

In [14]:
myNum = np.random.rand(25)

In [15]:
myReshaped = myNum.reshape(5,5)
myReshaped

array([[0.06812049, 0.67712025, 0.9294119 , 0.50204648, 0.55955464],
       [0.56139488, 0.11687655, 0.68420312, 0.70222953, 0.61169081],
       [0.79138802, 0.72761843, 0.67262595, 0.4736142 , 0.86691007],
       [0.42090291, 0.0483378 , 0.49968331, 0.12243445, 0.90927591],
       [0.98697061, 0.60127926, 0.6341252 , 0.70687566, 0.34751742]])