# Intermidiate stuff with numpy.

In [1]:
import numpy as np

In [2]:
myArray = np.arange(10,21)

In [3]:
myArray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
myArray[0]

10

In [5]:
myArray[1:4]

array([11, 12, 13])

In [6]:
myArray[:4]

array([10, 11, 12, 13])

In [7]:
myArray[:] = 50

In [8]:
myArray

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [9]:
# Isssue use .copy() method to copy the arrays.
copyArrauy =  myArray
myArray[0] = 12
copyArrauy

array([12, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])