In [1]:
import numpy as np

In [2]:
myTwoDArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
myTwoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
myTwoDArray[2][1]

8

In [5]:
myTwoDArray[:2,:2]

array([[1, 2],
       [4, 5]])

In [6]:
myTwoDArray[:2, 1:]

array([[2, 3],
       [5, 6]])

# Conditionals in numpy

In [7]:
myTwoDArray[myTwoDArray < 5]

array([1, 2, 3, 4])

In [8]:
myTwoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
myTwoDArray < 5

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

# Operations in numpy

In [11]:
newArray = np.array([1,2,3,4,5,6,7,8,9,10])

In [12]:
# Multiplying all values of array
newArray = newArray * 2

In [13]:
newArray

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
# Getting square root of numpy array
np.sqrt(newArray)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739, 4.        , 4.24264069, 4.47213595])